### ISSUE TITLE
[ISSUE]  Unhanded  framework failed case

### ISSUE THREAD

**Issue by yyrdl** [microsoft/frameworkcontroller#14] opened 2019-05-31 08:23 UTC
framework state should change to "FrameworkCompleted" when failed to pull image , but got "AttemptPreparing"

**Comment by yyrdl** [comment] 2019-05-31 08:26
I am working on that  ^_^

**Comment by yqwang-ms** [comment] 2019-05-31 17:45
Thanks yyrdl.
Could you please explian more details?

It may be caused by your retry policy, so the framework is retrying again and again to pull image, and then you will see preparing state in a large chance.

BTW, please next time @me, so that I can get email notification. :)

**Comment by fengyul** [comment] 2019-06-04 03:04
This also happened in another case when there is no resource like no GPU but needed in cluster. So would you like to add the pod events to the framework events to solve this?  @yyrdl

**Comment by yqwang-ms** [comment] 2019-06-04 03:57
@fengyul 
Pod Pending due to no resource (such as GPU), is by design should be AttemptPreparing.

K8S Event is unreliable compared with other object, so it should not be used to fix framework state. (Even though, I think this is not an issue until yyrdl explian more details)

**Comment by yqwang-ms** [comment] 2019-06-04 04:26
@yyrdl 
I have tried by myself to reproduce this.

If image cannot be pulled, K8S will keep the Pod in Pending state (without complete or retry it), so FrameworkController respect the Pod state, i.e. Pending, thus the whole Framework state is AttemptPreparing by design.

I also wonder whether K8S can provide a Pod spec option to let user specify if fail the pod when image not found. So this issue is more like a K8S new feature request, instead of FrameworkController bug.

If no concerns, I will close this issue.

```
yqwang@stcal-139:~$ kubectl describe pod batchsucceeded5ubuntu2-worker-0

Name:               batchsucceeded5ubuntu2-worker-0
Status:             **Pending**
IP:                 172.17.0.7
Controlled By:      ConfigMap/batchsucceeded5ubuntu2-attempt
Containers:
  ubuntu2:
    Container ID:
    Image:         ubuntu2:trusty
    Image ID:
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  **0**
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  3m14s                default-scheduler  Successfully assigned default/batchsucceeded5ubuntu2-worker-0 to minikube
  Normal   Pulling    95s (x4 over 3m13s)  kubelet, minikube  Pulling image "ubuntu2:trusty"
  Warning  Failed     95s (x4 over 3m12s)  kubelet, minikube  **Failed to pull image "ubuntu2:trusty": rpc error: code = Unknown desc = Error response from daemon: pull access denied for ubuntu2, repository does not exist or may require 'docker login'**
  Warning  Failed     95s (x4 over 3m12s)  kubelet, minikube  Error: **ErrImagePull**
  Warning  Failed     83s (x6 over 3m12s)  kubelet, minikube  Error: **ImagePullBackOff**
  Normal   BackOff    68s (x7 over 3m12s)  kubelet, minikube  **Back-off pulling image** "ubuntu2:trusty"
```

**Comment by yyrdl** [comment] 2019-06-04 05:38
@yqwang-ms  

At first ,  thanks for your help , I just come to work today   :) 

I think  about this carefully , and still regard it is an unhanded case.  If an image can't pull forever (such as not exist) , then the framework can't achieve either . The error should be reported to user,  and not just wait . Otherwise  the user will ask "why my framework is still waiting ,what's wrong with your platform?"  haha.   as developer , it's our duty to fix this. 

If we can handle this in the frameworkcontroller , I think it's a better choice than make a feature request to k8s .

@fengyul  we can describe the problem more generally:

*  The pod can't succeed forever because of something wrong in the preparing phase .
*  The  resource can not be satisfied forever (gpu ,npu ,fpga ....). 

I am not an English native speaker , I can't express what I think very well , please don't matter :)

**Comment by yqwang-ms** [comment] 2019-06-04 05:59
I think I get your point now:
The framework preparing state is right, but we need to a way to tell user why it is in preparing state.
Right?

For this, I think you can already achieve it, by directly forwarding the Pod events (and status) to end user, without changing any code about FrameworkController.
Right?

**Comment by fengyul** [comment] 2019-06-04 06:01
The state should be AttemptPreparing by the k8s designing for those cases. But for the users, they need to know what happens now. That's why I think the event is one of the solutions. If the frameworkController can reports the more events like pods, we can tell the reason why the framework is waiting. This is my opinion.  
Waiting for the final solution...
@yyrdl @yqwang-ms

**Comment by yqwang-ms** [comment] 2019-06-04 06:17
@fengyul you are right!
So, currently we have 2 solutions:
1. The FrameworkController wrapper (such as your WebServer), forwards the Pod events (and status) to end user.
2. FrameworkController itself forwards the Pod events to its Framework object's events. And the FrameworkController wrapper (such as your WebServer), forwards the Framework events to end user.

Option 1 has pros that:
1. No need to change FrameworkController code
2. No need to store duplicated events in ApiServer (etcd)
3. Align with other offical controller's behaiour
Such as statefulset, Pod events will not be forwarded to its statefulset events:
![image](https://user-images.githubusercontent.com/32826762/58855531-dcf7eb00-86d2-11e9-85d7-0f83c9cc057e.png)
But the k8s dashboard (like your WebServer), directly forwards the Pod events to its UI:
![image](https://user-images.githubusercontent.com/32826762/58855724-55f74280-86d3-11e9-9301-414254c0a719.png)

I think, to be conservative and align with K8S convention, we can first adopt 1, before possible premature optimization, i.e. option 2.

**Comment by yyrdl** [comment] 2019-06-04 08:42
@yqwang-ms  thanks for your advce ,that's helpfull

**Closed** 2019-06-04 08:42 UTC
